export const RightSliderData = [
    {
        image:
        'https://source.unsplash.com/pink-ceramic-bowl-besides-spoon-MHHAQR24tzc',
        alt:"1"

     },
     {
        image:
        'https://source.unsplash.com/strawberry-juice-beside-fruits-on-top-of-table-CpBBsda2eRI',
        alt:"2"
     },
     {
        image:
        'https://source.unsplash.com/white-and-black-ceramic-coffee-cup-on-white-saucer-cEJwMalRit8',
        alt:"3"
     },
     {
        image:
        'https://source.unsplash.com/burgers--GFCYhoRe48',
        alt:"4"
     },
     {
        image:
        'https://source.unsplash.com/hamburger-with-patty-pHeX8H9WQpY',
        alt:"5"
     },
     {
        image:
        'https://source.unsplash.com/bun-lettuce-and-chips-served-on-white-ceramic-plate-SFU3oiiC7iw',
        alt:"6"
     }
]