export const RightSliderData = [
    {
        image:
        'https://www.colombosevengin.com/wp-content/uploads/2017/02/colombo_21-1000x1498.jpg',
        alt:"1"

     },
     {
        image:
        'https://www.colombosevengin.com/wp-content/uploads/2017/01/colombo_18-1000x1498.jpg',
        alt:"2"
     },
     {
        image:
        'https://www.colombosevengin.com/wp-content/themes/bespoke_1-1/images/landscapes/02_right.jpg',
        alt:"3"
     },
     {
        image:
        'https://www.colombosevengin.com/wp-content/uploads/2017/01/colombo_12-1000x1498.jpg',
        alt:"4"
     },
     {
        image:
        'https://www.colombosevengin.com/wp-content/uploads/2017/01/colombo_02-1000x1498.jpg',
        alt:"5"
     },
     {
        image:
        'https://source.unsplash.com/bun-lettuce-and-chips-served-on-white-ceramic-plate-SFU3oiiC7iw',
        alt:"6"
     }
]